package com.michaldrabik.ui_navigation.java

object NavigationArgs {
  const val ARG_ID = "ARG_ID"
  const val ARG_SHOW_ID = "ARG_SHOW_ID"
  const val ARG_MOVIE_ID = "ARG_MOVIE_ID"
  const val ARG_EPISODE_ID = "ARG_EPISODE_ID"
  const val ARG_COMMENT_ID = "ARG_COMMENT_ID"

  const val ARG_LIST = "ARG_LIST"
  const val ARG_COMMENT = "ARG_COMMENT"
  const val ARG_COMMENT_ACTION = "ARG_COMMENT_ACTION"
  const val ARG_FAMILY = "ARG_FAMILY"
  const val ARG_TYPE = "ARG_TYPE"
  const val ARG_PICK_MODE = "ARG_PICK_MODE"
  const val ARG_CUSTOM_IMAGE_CLEARED = "ARG_CUSTOM_IMAGE_CLEARED"
  const val ARG_REPLY_USER = "ARG_REPLY_USER"

  const val REQUEST_CUSTOM_IMAGE = "REQUEST_CUSTOM_IMAGE"
  const val REQUEST_COMMENT = "REQUEST_COMMENT"
  const val REQUEST_EPISODE_DETAILS = "REQUEST_EPISODE_DETAILS"

  const val ACTION_NEW_COMMENT = "ACTION_NEW_COMMENT"
  const val ACTION_RATING_CHANGED = "ACTION_RATING_CHANGED"
  const val ACTION_EPISODE_WATCHED = "ACTION_EPISODE_WATCHED"
  const val ACTION_EPISODE_TAB_SELECTED = "ACTION_EPISODE_TAB_SELECTED"

  const val REQUEST_CREATE_LIST = "REQUEST_CREATE_LIST"
  const val REQUEST_MANAGE_LISTS = "REQUEST_MANAGE_LISTS"
}
