package com.michaldrabik.ui_model

enum class Network(
  vararg val channels: String,
) {
  ABC(
    "ABC",
    "ABC (AU)",
    "ABC (JA)",
    "ABC (US)",
    "ABC Comedy",
    "ABC Family",
    "ABC KIDS",
    "ABC Me",
    "ABC News",
    "ABC News 24",
    "ABC Spark",
    "ABC TV",
    "ABC TV Plus",
  ),
  AMC(
    "AMC",
    "AMC+"
  ),
  APPLE(
    "Apple",
    "Apple TV+",
    "Apple Music"
  ),
  AMAZON(
    "Amazon",
    "Amazon (Japan)",
    "Amazon Freevee",
    "Amazon Kids+",
    "Amazon Prime Video",
    "Amazon Studios",
    "Amazon miniTV"
  ),
  BBC(
    "BBC",
    "BBC America",
    "BBC Canada",
    "BBC Choice",
    "BBC Earth",
    "BBC First",
    "BBC Four",
    "BBC HD",
    "BBC Kids",
    "BBC Knowledge",
    "BBC Music",
    "BBC News",
    "BBC One",
    "BBC Prime",
    "BBC Red Button",
    "BBC Scotland",
    "BBC Television",
    "BBC Three",
    "BBC Two",
    "BBC UKTV",
    "BBC Wales",
    "BBC World News",
    "BBC Worldwide",
    "BBC iPlayer",
  ),
  CBS(
    "CBS",
    "CBS All Access",
    "CBS News",
    "CBS Reality",
    "CBS Reality (UK)",
    "CBS.com",
  ),
  CW("CW", "The CW"),
  DISCOVERY(
    "Discovery",
    "Discovery (NL)",
    "Discovery (US)",
    "Discovery Asia",
    "Discovery Channel",
    "Discovery Channel (AU)",
    "Discovery Channel (Asia)",
    "Discovery Channel (CA)",
    "Discovery Channel (Canada)",
    "Discovery Channel (PL)",
    "Discovery Channel (SE)",
    "Discovery Channel (UK)",
    "Discovery Communications",
    "Discovery Family",
    "Discovery GO",
    "Discovery HD World",
    "Discovery Health Channel",
    "Discovery History",
    "Discovery JEET",
    "Discovery Kids",
    "Discovery Life",
    "Discovery MAX",
    "Discovery Real Time",
    "Discovery Science",
    "Discovery Shed",
    "Discovery Turbo",
    "Discovery Turbo UK",
    "Discovery UK",
    "Discovery+"
  ),
  DISNEY(
    "Disney",
    "Disney Channel",
    "Disney Channel (DE)",
    "Disney Channel (FR)",
    "Disney Channel (IT)",
    "Disney Channel (UK)",
    "Disney Channel (US)",
    "Disney Cinemagic",
    "Disney Junior",
    "Disney Junior (UK)",
    "Disney Television Animation",
    "Disney XD",
    "Disney XD (Latin America)",
    "Disney+",
    "Disney+ Hotstar"
  ),
  HBO(
    "HBO",
    "HBO Asia",
    "HBO Brasil",
    "HBO Canada",
    "HBO España",
    "HBO Europe",
    "HBO Family",
    "HBO Latin",
    "HBO America",
    "HBO Magyarország",
    "HBO Max",
    "HBO Nordic",
  ),
  FOX(
    "FOX",
    "FOX (US)",
    "FOX España",
    "FOX Reality",
    "FOX SPORTS",
    "FOX Traveller",
    "FOX Türkiye",
    "FOX Türkiye (TR)",
    "FOX+",
  ),
  HULU("Hulu", "Hulu Japan"),
  ITV(
    "ITV",
    "ITV Encore",
    "ITV Granada",
    "ITV Wales"
  ),
  NBC(
    "NBC",
    "NBC News Studios",
    "NBC Universo",
    "NBCSN",
    "NBCUniversal"
  ),
  NETFLIX("Netflix"),
  SHOWTIME("Showtime"),
  RAKUTEN("Rakuten TV")
}
